sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
after_success:
  - chmod +x send-to-discord.sh
  - ./send-to-discord.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - chmod +x send-to-discord.sh
  - ./send-to-discord.sh failure $DISCORD_WEBHOOK_URL