{
 "title": "OOTB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alfresco Active Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alfresco_active_sessions{instance=\"hostname:port\",type=\"NumActive\"}",
     "legendFormat": "NumActive"
    }
   ]
  },
  {
   "title": "Maximum number of active sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "alfresco_active_sessions{instance=\"hostname:port\",type=\"MaxActive\"}",
     "legendFormat": "MaxActive"
    }
   ]
  },
  {
   "title": "Idle Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alfresco_active_sessions{instance=\"hostname:port\",type=\"NumIdle\"}",
     "legendFormat": "NumIdle"
    }
   ]
  }
 ]
}