name: Java CI

on:
  push:
    paths-ignore:
      - 'grafana/**'
      - 'images/**'
      - '*.md'
      - '**/*.md'
      - '*.sh'
      - '**/*.sh'
      - '*.bat'
      - '**/*.bat'
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package